# -*- coding: utf-8 -*-
"""DeepSeek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1asnnJvnZ3PuQ_gRr5Ww4E-E7S_G4U-FF
"""

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

!pip install transformers accelerate

from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"  # adjust for the variant you want

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             device_map="auto",
                                             torch_dtype="auto")

# save locally if you want
model.save_pretrained("/content/deepseek_r1_distill_qwen1.5b")
tokenizer.save_pretrained("/content/deepseek_r1_distill_qwen1.5b")

prompt = "Give me a short introduction to large language model."

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=512
)

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
print(response)

